-- MySQL Script generated by MySQL Workbench
-- Tue Sep 13 08:45:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema classic_etrella
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `classic_etrella` ;

-- -----------------------------------------------------
-- Schema classic_etrella
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classic_etrella` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `classic_etrella` ;

-- -----------------------------------------------------
-- Table `classic_etrella`.`dimension_tiempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classic_etrella`.`dimension_tiempo` ;

CREATE TABLE IF NOT EXISTS `classic_etrella`.`dimension_tiempo` (
  `iddimension_tiempo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `ano` INT NULL DEFAULT NULL,
  `mes` INT NULL DEFAULT NULL,
  PRIMARY KEY (`iddimension_tiempo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `classic_etrella`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classic_etrella`.`employees` ;

CREATE TABLE IF NOT EXISTS `classic_etrella`.`employees` (
  `employees_id` INT NOT NULL AUTO_INCREMENT,
  `employeeNumber` INT NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `extension` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `officeCode` VARCHAR(10) NOT NULL,
  `reportsTo` INT NULL DEFAULT NULL,
  `jobTitle` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `addressLine1` VARCHAR(50) NOT NULL,
  `addressLine2` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NOT NULL,
  `postalCode` VARCHAR(15) NOT NULL,
  `territory` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`employees_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classic_etrella`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classic_etrella`.`orders` ;

CREATE TABLE IF NOT EXISTS `classic_etrella`.`orders` (
  `orders_id` INT NOT NULL AUTO_INCREMENT,
  `orderNumber` INT NOT NULL,
  `orderDate` DATE NOT NULL,
  `requiredDate` DATE NOT NULL,
  `shippedDate` DATE NULL DEFAULT NULL,
  `status` VARCHAR(15) NOT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  `customerNumber` INT NOT NULL,
  `detalle_orderNumber` INT NOT NULL,
  `detalle_productCode` VARCHAR(15) NOT NULL,
  `detelle_quantityOrdered` INT NOT NULL,
  `detalle_priceEach` DECIMAL(10,2) NOT NULL,
  `detalle_orderLineNumber` SMALLINT NOT NULL,
  PRIMARY KEY (`orders_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `customerNumber` ON `classic_etrella`.`orders` (`customerNumber` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `classic_etrella`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classic_etrella`.`products` ;

CREATE TABLE IF NOT EXISTS `classic_etrella`.`products` (
  `productCode` VARCHAR(15) NOT NULL,
  `productName` VARCHAR(70) NOT NULL,
  `productLine` VARCHAR(50) NOT NULL,
  `productScale` VARCHAR(10) NOT NULL,
  `productVendor` VARCHAR(50) NOT NULL,
  `productDescription` TEXT NOT NULL,
  `quantityInStock` SMALLINT NOT NULL,
  `buyPrice` DECIMAL(10,2) NOT NULL,
  `MSRP` DECIMAL(10,2) NOT NULL,
  `detalle_productLine` VARCHAR(50) NULL DEFAULT NULL,
  `textDescription` VARCHAR(4000) NULL DEFAULT NULL,
  `htmlDescription` MEDIUMTEXT NULL DEFAULT NULL,
  `image` MEDIUMBLOB NULL DEFAULT NULL,
  `products_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`products_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classic_etrella`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classic_etrella`.`Venta` ;

CREATE TABLE IF NOT EXISTS `classic_etrella`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Unidades` VARCHAR(45) NOT NULL,
  `orders_orders_id` INT NOT NULL,
  `employees_employees_id` INT NOT NULL,
  `products_products_id` INT NOT NULL,
  `dimension_tiempo_iddimension_tiempo` INT NOT NULL,
  PRIMARY KEY (`idVenta`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
